### ISSUE TITLE
Logo Design For HLSPlayback

### ISSUE THREAD

**Issue by zularizal** [lashawnmcghee/HLSPlayback#1]
Hi @lashawnmcghee , I'm a graphic designer, after I review your project, I'm interested in your project and I want to contribute by creating a logo/icon for your project. And this is free for you. What do you think?

**Comment by lashawnmcghee** [comment]
Hi,

That would be great!
I am going to extend the project this week.
It will be nice to see what you come up with :).

Thanks,
-LaShawn
